openapi: 3.1.1
info:
  version: 1.0.0
  title: Test API
servers:
  -
    url: http://127.0.0.1:8000/api
security: []
tags: []
x-tagGroups: []
components: 
  securitySchemes: {}
  schemas: {}
paths: {}